USE Kleague;

-- [DML_QUERY, P.19] team_id가 K07인 선수의 아이디, 이름, 백넘버를 출력하시오
SELECT PLAYER_ID, PLAYER_NAME, BACK_NO
FROM PLAYER
WHERE TEAM_ID = 'K07';

-- [DML_QUERY, P.41] 브라질출신 MF와 러시아출신 FW인 선수의 이름, 팀 아이디, 포지션, 국가를 출력하시오.
SELECT PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM PLAYER
WHERE (NATION, POSITION) IN (('브라질', 'MF'), ('러시아', 'FW'));

-- [DML_QUERY, P.44] 장씨 선수의 정보를 출력하세요
SELECT *
FROM PLAYER
WHERE PLAYER_NAME LIKE '장%';

-- [DML_QUERY, P.47] 포지션이 존재하지 않는 선수의 이름과 포지션, 팀 아이디를 출력하세요
SELECT PLAYER_NAME, POSITION, TEAM_ID
FROM PLAYER
WHERE POSITION IS NULL;

-- [(추가)DML_QUERY, P.55] 포지션별 인원수, 키 데이터수, 최대키, 최소키, 평균키를 구하세요
SELECT POSITION, COALESCE(COUNT(*), 0), COALESCE(COUNT(HEIGHT), 0), 
	   MAX(HEIGHT), MIN(HEIGHT), ROUND(AVG(HEIGHT), 2)
FROM PLAYER
GROUP BY POSITION;

-- [DML_QUERY, P.64] 동명이인인 선수이름을 출력하시오
SELECT PLAYER_NAME
FROM PLAYER
GROUP BY PLAYER_NAME HAVING COUNT(*) >= 2;

SELECT PLAYER_NAME, COUNT(*) AS 동명이인수
FROM PLAYER
GROUP BY PLAYER_NAME HAVING 동명이인수 >= 2;

-- [DML_QUERY, P.65] 평균키가 180이상인 포지션을 출력하시오
SELECT POSITION
FROM PLAYER
GROUP BY POSITION HAVING AVG(HEIGHT) >= 180;

-- [DML_QUERY, P.67] 팀별로 각각의 생월에 대한 선수의 평균 키를 구하시오
SELECT TEAM_ID,
	   ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=1 THEN HEIGHT END), 2) AS MO1,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=2 THEN HEIGHT END), 2) AS MO2,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=3 THEN HEIGHT END), 2) AS MO3,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=4 THEN HEIGHT END), 2) AS MO4,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=5 THEN HEIGHT END), 2) AS MO5,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=6 THEN HEIGHT END), 2) AS MO6,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=7 THEN HEIGHT END), 2) AS MO7,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=8 THEN HEIGHT END), 2) AS MO8,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=9 THEN HEIGHT END), 2) AS MO9,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=10 THEN HEIGHT END), 2) AS M10,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=11 THEN HEIGHT END), 2) AS M11,
       ROUND(AVG(CASE WHEN MONTH(BIRTH_DATE)=12 THEN HEIGHT END), 2) AS M12
FROM PLAYER
GROUP BY TEAM_ID;

-- [DML_QUERY, P.73] 팀별로 각 포지션에 대한 인원수, 그리고 팀의 전체 인원수를 구하시오. 단 데이터가 없는 경우는 0으로 표시한다.
SELECT TEAM_ID, COALESCE(COUNT(PLAYER_ID), 0),
       COALESCE(COUNT(CASE WHEN POSITION = 'MF' THEN PLAYER_ID END), 0) AS 'MF',
       COALESCE(COUNT(CASE WHEN POSITION = 'FW' THEN PLAYER_ID END), 0) AS 'FW',
       COALESCE(COUNT(CASE WHEN POSITION = 'DS' THEN PLAYER_ID END), 0) AS 'DS',
	   COALESCE(COUNT(CASE WHEN POSITION = 'GK' THEN PLAYER_ID END), 0) AS 'GK'
FROM PLAYER
GROUP BY TEAM_ID;

-- [DML_QUERY, P.88] 가장 규모가 큰 3개의 경기장의 아이디, 이름, 좌석수를 출력하시오
SELECT STADIUM_ID, STADIUM_NAME, SEAT_COUNT
FROM STADIUM
ORDER BY SEAT_COUNT DESC, STADIUM_NAME
LIMIT 3;




