USE Kleague;
                
-- [DML_Subquery P.17] 선수들의 평균 키보다 작은 선수들의 이름, 포지션, 백넘버를 출력
SELECT PLAYER_NAME, POSITION, BACK_NO
FROM PLAYER
WHERE HEIGHT <= (SELECT AVG(HEIGHT) FROM PLAYER);

-- [DML_Subquery P.18] 정현수 선수의 소속팀의 연고지명, 팀명, 영문팀명을 출력
SELECT REGION_NAME, TEAM_NAME, E_TEAM_NAME
FROM TEAM
WHERE TEAM_ID = ANY (SELECT TEAM_ID FROM PLAYER WHERE PLAYER_NAME = '정현수');

-- [DML_Subquery P.21] 각 팀에서 제일 키가 작은 선수들의 팀아이디, 선수명, 포지션, 백넘버, 키를 출력
SELECT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM PLAYER
WHERE (TEAM_ID, HEIGHT) IN (SELECT TEAM_ID, MIN(HEIGHT) FROM PLAYER GROUP BY TEAM_ID);

-- [DML_Subquery P.25] 각 팀에서 제일 키가 큰 선수들의 팀 아이디, 이름, 키를 출력
SELECT TEAM_ID, PLAYER_NAME, HEIGHT
FROM PLAYER
WHERE (TEAM_ID, HEIGHT) IN (SELECT TEAM_ID, MAX(HEIGHT) FROM PLAYER GROUP BY TEAM_ID);

-- [DML_Subquery P.29] 소속 팀의 평균 키보다 작은 선수들의 팀 아이디, 이름, 포지션, 백넘버, 키를 출력
SELECT TEAM_ID, PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM PLAYER AS X
WHERE X.HEIGHT < (SELECT AVG(Y.HEIGHT) FROM PLAYER AS Y WHERE X.TEAM_ID = Y.TEAM_ID)
ORDER BY X.TEAM_ID, X.HEIGHT;

-- [DML_Subquery P.30] 브라질 혹은 러시아 출신 선수가 있는 팀을 검색(연관 서브커리 사용), 팀아이디, 팀명을 출력
SELECT TEAM_ID, TEAM_NAME
FROM TEAM
WHERE TEAM_ID = ANY (SELECT TEAM_ID FROM PLAYER WHERE NATION IN ('브라질', '러시아'));

-- [DML_Subquery P.32] 20120501부터 20120502 사이에 경기가 열렸던 경기장을 조회(연관 서브쿼리 사용), 경기장아이디, 경기장명을 출력
SELECT STADIUM_NAME
FROM STADIUM
WHERE STADIUM_ID IN (SELECT STADIUM_ID FROM SCHEDULE WHERE SCHE_DATE BETWEEN '2012-05-01' AND '2012-05-02');

-- [DML_Subquery P.34] 포지션이 GK인 선수들을 검색(연관 서브쿼리 사용)
SELECT PLAYER_NAME, POSITION
FROM PLAYER AS X
WHERE PLAYER_ID IN (SELECT PLAYER_ID FROM PLAYER WHERE POSITION='GK');

SELECT TEAM_ID, PLAYER_NAME, BACK_NO, HEIGHT
FROM PLAYER AS X
WHERE PLAYER_ID IN (SELECT PLAYER_ID FROM PLAYER AS Y WHERE X.PLAYER_ID = Y.PLAYER_ID AND POSITION = 'GK');

-- [DML_Subquery P.43] 팀 아이디, 선수명, 키, 소속 팀의 평균키를 출력
SELECT TEAM_ID, PLAYER_NAME, HEIGHT,
       (SELECT AVG(HEIGHT) FROM PLAYER AS Y WHERE X.TEAM_ID = Y.TEAM_ID) AS 팀평균키
FROM PLAYER AS X
ORDER BY TEAM_ID;

-- [DML_Subquery P.44] 팀 아이디, 팀명, 팀 인원수를 출력
SELECT TEAM_ID, TEAM_NAME,
       (SELECT COUNT(*) FROM PLAYER AS Y WHERE X.TEAM_ID = Y.TEAM_ID) AS 팀인원수
FROM TEAM AS X
ORDER BY TEAM_ID;

-- [DML_Subquery P.45] 팀 아이디, 팀명, 각 팀의 마지막 경기가 진행된 날짜를 출력
SELECT TEAM_ID, TEAM_NAME,
       (SELECT MAX(SCHE_DATE) FROM SCHEDULE AS Y WHERE X.TEAM_ID = Y.HOMETEAM_ID OR X.TEAM_ID = Y.AWAYTEAM_ID) AS '최종 경기일'
FROM TEAM AS X;

-- [DML_Subquery P.49] 포지션이 MF인 선수들의 소속팀명 및 선수이름과 백넘버를 출력
SELECT TEAM_NAME, PLAYER_NAME, BACK_NO
FROM (SELECT TEAM_ID, PLAYER_NAME, BACK_NO
      FROM PLAYER
	  WHERE POSITION = 'MF') AS P, TEAM AS T
WHERE P.TEAM_ID = T.TEAM_ID
ORDER BY TEAM_NAME, PLAYER_NAME;

-- [DML_Subquery P.50] 키가 제일 큰 5명의 선수들의 이름, 포지션, 백넘버를 출력
SELECT PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM (SELECT PLAYER_NAME, POSITION, BACK_NO, HEIGHT
      FROM PLAYER
      WHERE HEIGHT IS NOT NULL
      ORDER BY HEIGHT DESC) AS TEMP
LIMIT 5;

-- [DML_Subquery P.52] K02 팀의 평균키보다 평균키가 작은 팀의 이름과 해당 팀의 평균키르 출력
SELECT TEAM_ID, TEAM_NAME, AVG(HEIGHT)
FROM TEAM JOIN PLAYER USING (TEAM_ID)
GROUP BY TEAM_ID
HAVING AVG(HEIGHT) < (SELECT AVG(HEIGHT) FROM PLAYER WHERE TEAM_ID='K02');
